WIDTH = 10
HEIGHT = 20
SCALE = 30

FPS = 60
INITIAL_SPEED_DELAY = FPS // 2

ELEMENT_SIZE = 28
ELEMENT_RADUIS = 3

SCREEN_COLOR = "black"
SNAKE_COLOR = "blue"
APPLE_COLOR = "red"
SCORE_COLOR = "white"
GAME_OVER_COLOR = "red"